server:
  port: 7902

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:db_users
    username: sa
    password:
    driverClassName: org.h2.Driver
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  application:
    name: provider

eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html #配置api接口文档 ${server.port}为该服务的端口号
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

logging:
  level:
    root: INFO
    com.masm.cloud: DEBUG