server:
  port: 7901

user:
  path: http://provider/findById/

spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
#      defaultZone: http://root:123456@springcloud1:8761/eureka/,http://root:123456@springcloud2:8762/eureka/
      defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #自定义使用随机策略

logging:
  level:
    com.masm: DEBUG
