server:
  port: 8761

# 安全认证的配置
security:
  basic:
    enabled: true
  user:
    name: root  # 用户名
    password: 123456   # 用户密码

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka # 安全的注册地址